---
title: Niklas Jordan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/writing/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
Site-Name: Niklas Jordan &middot; UX Professional
MetaDescription: I help good organizations create products and services people need
  (and love) that have a good impact on their mission and the world. I do this through
  smart research, experience and psychology.
Twitter: "@niklas_jordan"
GooglePlus: https://plus.google.com/u/0/104211211117831167754
navigation:
- title: Who I am & what I do
  url: "/who-i-am.html"
- title: UX Review
  url: "/ux-review.html"
- title: Contact
  url: "/contact.html"
gems:
- jemoji
